**Tarefa 1: Obtenção dos conjunto de dados e suas informações**

1 - Fazer download nesse [link](https://www.gov.br/prf/pt-br/acesso-a-informacao/dados-abertos/dados-abertos-da-prf) de todos os conjuntos de dados de acidentes e de multas, entre os anos
de 2018 e 2025, além dos dicionários de dados relacionados;

---

Download dos arquivos hospedados no Mega (via link de download direto) utilizando megadl.

Dessa forma é possível economizar armazenamento local e fazer upload do notebook para o GitHub sem erros de limite de armazenamento.

Os arquivos estão armazenados em:
- INFRAÇÕES (MULTAS): https://mega.nz/folder/NnpHxSaD#zVB4QFDj03QeT_F0BR6tUQ

- ACIDENTES - AGRUPADOS POR OCORRÊNCIA: https://mega.nz/folder/RqZHyLgS#7sA4uIbpQP_-cif43HpUEQ

In [1]:
# Este bloco de código é dedicado ao download dos datasets de INFRAÇÕES 2018, 2021 e 2025
# Cada arquivo de saída foi nomeado conforme o ano da extração dos dados
# Os arquivos após o download estarão na pasta /content/infracoes

!apt-get install -y megatools # Instala o pacote necessário para fazer a requisição de download
!mkdir infracoes # Cria dinamicamente a pasta para armazenar os arquivos

!megadl "https://mega.nz/file/96wmRJRD#WPmLGUJYa84aYR3Qrnrko7zthxGuRL5VuuwK1g62jwI" \
  --path /content/infracoes/infracoes_2018.zip

!megadl "https://mega.nz/file/k3RS1JwZ#jf0hnP6Jy9K9SzH1_vyS-BaQlMF4vO5n2G-a6Ge0vvI" \
  --path /content/infracoes/infracoes_2021.zip

!megadl "https://mega.nz/file/1nwTSTBC#OHmSACYGagRV2ZMAl7F9ktTu5PX3uUbpC_-47VgRcSo" \
  --path /content/infracoes/infracoes_2025.zip

print("\033[32mDownload finalizado!\033[m")

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
megatools is already the newest version (1.10.3-1build1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
Downloaded infracoes_2018.zip
Downloaded infrações_2021.zip
Downloaded infrações_2025.zip
Download finalizado!

In [2]:
# Este bloco de código é dedicado ao download dos datasets de ACIDENTES AGRUPADOS POR OCORRÊNCIA 2018, 2021 e 2025
# Cada arquivo de saída foi nomeado conforme o ano da extração dos dados
# Os arquivos após o download estarão na pasta /content/acidentes

!mkdir acidentes # Cria dinamicamente a pasta para armazenar os arquivos

!megadl "https://mega.nz/file/VnIG0SgI#7RX1owbScp7IgRU06UwvsKZUpkZyDstV73G7jKYf6nY" \
  --path /content/acidentes/acidentes_2018.zip

!megadl "https://mega.nz/file/1mgwwAKL#0ff5c_m-SUtZJhRGSn_PTSW23HyJ3hhGtXq3s9Hat6w" \
  --path /content/acidentes/acidentes_2021.zip

!megadl "https://mega.nz/file/AioT2QwY#UDcswOFWQPvxAL5eiOy8xusiHD9fZmAwlfIuip2eP7M" \
  --path /content/acidentes/acidentes_2025.zip

print("\033[32mDownload finalizado!\033[m")

Downloaded datatran2018.zip
Downloaded datatran2021.zip
Downloaded datatran2025.zip
Download finalizado!

In [3]:
# Padronização de todos os datasets antes de prosseguir com as demais questões
import zipfile
import shutil
import os

# Funções úteis

def new_dir(caminho, pastas):
  """
    Cria novos diretórios a partir de um array
    e extrai os arquivos zipados dinamicamente
  """
  try:
    for pasta in pastas:
      # Cria uma nova pasta caso ainda não exista
      if not os.path.isdir(f"{caminho}/{pasta}"):
        os.mkdir(f"{caminho}/{pasta}")

      # Extrai os arquivos dinamicamente
      arquivo = f"{caminho}/{pasta}.zip"
      with zipfile.ZipFile(f"{arquivo}") as dataset:
        dataset.extractall(path=f"{caminho}/{pasta}")
    print("\033[32mArquivos extraídos com sucesso!\033[m")

  except Exception as e:
    print(f"\033[31mErro ao extrair os arquivos: {e}\033[m")

def move_file(caminho, pastas):
  """
    Percorre os diretórios raiz e, se houver
    subpastas, move os arquivos para a pasta
    raiz e remove a subpasta
  """
  try:
    for pasta in pastas:
      pasta_raiz = f"{caminho}/{pasta}"
      # Verifica se há uma subpasta na pasta atual
      subdir = [name for name in os.listdir(pasta_raiz) if os.path.isdir(os.path.join(pasta_raiz, name))]
      if subdir:
        subpasta = f"{pasta_raiz}/{subdir[0]}"
        for arquivo in os.listdir(subpasta):
          if arquivo.endswith(".csv"):
            origem = os.path.join(subpasta, arquivo)
            destino = os.path.join(pasta_raiz, arquivo)
            shutil.move(origem, destino)
        # Remove a subpasta
        shutil.rmtree(subpasta)
    print("\033[32mArquivos movidos com sucesso!\033[m")

  except Exception as e:
    print(f"\033[31mErro ao mover arquivos de subpastas: {e}\033[m")

print("\033[32mImportações e carregamento de funções realizadas com sucesso!\033[m")

Importações e carregamento de funções realizadas com sucesso!

In [4]:
# Datasets de INFRAÇÕES (MULTAS) 2018, 2021 e 2025
# Criando as pastas e extraindo os arquivos .zip de infrações 2018-2025
pastas = [
    "infracoes_2018", "infracoes_2021", "infracoes_2025"
]

infra_path = "/content/infracoes"

# Cria pastas individuais para cada infração por ano chamando a função new_dir
new_dir(infra_path, pastas)

# Algumas pastas não seguem o padrão de infracoes_20XX_XX.csv
# É necessário realizar o tratamento individual dessas pastas
# para que todos os datasets sigam o mesmo modelo

# Checa se dentro do diretório raiz há uma subpasta
move_file(infra_path, pastas)

Arquivos extraídos com sucesso!
Arquivos movidos com sucesso!

In [5]:
# Alguns arquivos não seguem o padrão de infracoes_ANO_MES.csv
# esses arquivos precisam ser renomeados para se adequar ao padrão

anos = [
    "2018", "2021", "2025"
]

meses = ["jan", "fev", "mar", "abr", "mai", "jun",
         "jul", "ago", "set", "out", "nov", "dez"]

# Laço para renomear arquivos
for i, pasta in enumerate(pastas):
    caminho_pasta = f"{infra_path}/{pasta}"

    for arquivo in os.listdir(caminho_pasta):
        nome, ext = os.path.splitext(arquivo)

        # Arquivo no padrão correto —> ignora
        if nome.startswith("infracoes_"):
            continue

        # Arquivo no formato infraçoes_ANO_MES.csv
        elif nome.startswith("infraçoes_"):
            novo_nome = nome.replace("infraçoes_", "infracoes_") + ".csv"

        # Arquivo no formato infraçoesANO_MES.csv
        elif nome.startswith("infraçoes"):
            novo_nome = nome.replace("infraçoes", "infracoes_") + ".csv"

        # Arquivo no formato MES.csv
        elif nome in meses:
            mes_num = meses.index(nome) + 1
            novo_nome = f"infracoes_{anos[i]}_{mes_num:02d}.csv"

        os.rename(
            os.path.join(caminho_pasta, arquivo),
            os.path.join(caminho_pasta, novo_nome)
        )

print("\033[32mArquivo renomeados com sucesso!\033[m")

Arquivo renomeados com sucesso!

In [6]:
# Datasets de ACIDENTES 2018, 2021 e 2025
pastas_acidentes = [
    "acidentes_2018", "acidentes_2021", "acidentes_2025"
]

aci_path = "/content/acidentes"

# Cria pastas individuais para cada acidente por ano chamando a função new_dir
new_dir(aci_path, pastas_acidentes)

Arquivos extraídos com sucesso!

2 - Conferir se as variáveis são as mesmas em todos os anos, para cada um dos cenários e levantar
as diferenças entre a lista de variáveis do conjunto de dados de acidentes e de multas (nessa ação
é necessário o auxílio do dicionário de dados, uma vez que variáveis podem ter nomenclaturas
distintas, porém, mesmo significado).

In [7]:
import pandas as pd
# Algumas colunas dos datasets de INFRAÇÕES possuem nomes distintos
infra_path = "/content/infracoes"

# Mapeamento das colunas de 2018 para o padrão dos demais anos
colunas_2018 = {
    "dat_infracao":             "Data da Infração (DD/MM/AAAA)",
    "tip_abordagem":            "Indicador de Abordagem",
    "ind_assinou_auto":         "Assinatura do Auto",
    "ind_veiculo_estrangeiro":  "Indicador Veiculo Estrangeiro",
    "ind_sentido_trafego":      "Sentido Trafego",
    "uf_placa":                 "UF Placa",
    "uf_infracao":              "UF Infração",
    "num_br_infracao":          "BR Infração",
    "num_km_infracao":          "Km Infração",
    "nom_municipio":            "Município",
    "cod_infracao":             "Código da Infração",
    "descricao_abreviada":      "Descrição Abreviada Infração",
    "enquadramento":            "Enquadramento da Infração",
    "data_inicio_vigencia":     "Início Vigência da Infração",
    "data_fim_vigencia":        "Fim Vigência Infração",
    "med_realizada":            "Medição Infração",
    "med_considerada":          "Medição Considerada",
    "exc_verificado":           "Excesso Verificado",
    "especie":                  "Descrição Especie Veículo",
    "nome_veiculo_marca":       "Descrição Marca Veículo",
    "nom_modelo_veiculo":       "Descrição Modelo Veiculo",
    "hora":                     "Hora Infração",
}

# INFRAÇÕES 2018
infra_2018_datasets = [
    f"{infra_path}/infracoes_2018/infracoes_2018_01.csv", f"{infra_path}/infracoes_2018/infracoes_2018_02.csv",
    f"{infra_path}/infracoes_2018/infracoes_2018_03.csv", f"{infra_path}/infracoes_2018/infracoes_2018_04.csv",
    f"{infra_path}/infracoes_2018/infracoes_2018_05.csv", f"{infra_path}/infracoes_2018/infracoes_2018_06.csv",
    f"{infra_path}/infracoes_2018/infracoes_2018_07.csv", f"{infra_path}/infracoes_2018/infracoes_2018_08.csv",
    f"{infra_path}/infracoes_2018/infracoes_2018_09.csv", f"{infra_path}/infracoes_2018/infracoes_2018_10.csv",
    f"{infra_path}/infracoes_2018/infracoes_2018_11.csv", f"{infra_path}/infracoes_2018/infracoes_2018_12.csv",
]

infra_2018 = [pd.read_csv(arquivo,sep=",",encoding="ISO-8859-1", low_memory=False) for arquivo in infra_2018_datasets]
df_infra_2018 = pd.concat(infra_2018, ignore_index=True)
df_infra_2018.rename(columns=colunas_2018, inplace=True)

df_infra_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7356159 entries, 0 to 7356158
Data columns (total 22 columns):
 #   Column                         Dtype
---  ------                         -----
 0   Data da Infração (DD/MM/AAAA)  object
 1   Indicador de Abordagem         object
 2   Assinatura do Auto             object
 3   Indicador Veiculo Estrangeiro  object
 4   Sentido Trafego                object
 5   UF Placa                       object
 6   UF Infração                    object
 7   BR Infração                    int64
 8   Km Infração                    int64
 9   Município                      object
 10  Código da Infração             int64
 11  Descrição Abreviada Infração   object
 12  Enquadramento da Infração      object
 13  Início Vigência da Infração    object
 14  Fim Vigência Infração          object
 15  Medição Infração               float64
 16  Medição Considerada            float64
 17  Excesso Verificado             float64
 18  Descrição Especie Veículo      object
 19  Descrição Marca Veículo        object
 20  Descrição Modelo Veiculo       object
 21  Hora Infração                  object
dtypes: float64(3), int64(3), object(16)
memory usage: 1.2+ GB

In [8]:
# INFRAÇÕES 2021
infra_2021_datasets = [
    f"{infra_path}/infracoes_2021/infracoes_2021_01.csv", f"{infra_path}/infracoes_2021/infracoes_2021_02.csv",
    f"{infra_path}/infracoes_2021/infracoes_2021_03.csv", f"{infra_path}/infracoes_2021/infracoes_2021_04.csv",
    f"{infra_path}/infracoes_2021/infracoes_2021_05.csv", f"{infra_path}/infracoes_2021/infracoes_2021_06.csv",
    f"{infra_path}/infracoes_2021/infracoes_2021_07.csv", f"{infra_path}/infracoes_2021/infracoes_2021_08.csv",
    f"{infra_path}/infracoes_2021/infracoes_2021_09.csv", f"{infra_path}/infracoes_2021/infracoes_2021_10.csv",
    f"{infra_path}/infracoes_2021/infracoes_2021_11.csv", f"{infra_path}/infracoes_2021/infracoes_2021_12.csv",
]

infra_2021 = [pd.read_csv(arquivo,sep=";",encoding="ISO-8859-1", low_memory=False) for arquivo in infra_2021_datasets]
df_infra_2021 = pd.concat(infra_2021, ignore_index=True)

df_infra_2021.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5241299 entries, 0 to 5241298
Data columns (total 22 columns):
 #   Column                         Dtype
---  ------                         -----
 0   Número do Auto                 object
 1   Data da Infração (DD/MM/AAAA)  object
 2   Indicador de Abordagem         object
 3   Assinatura do Auto             object
 4   Indicador Veiculo Estrangeiro  object
 5   Sentido Trafego                object
 6   UF Infração                    object
 7   BR Infração                    int64
 8   Km Infração                    int64
 9   Município                      object
 10  Código da Infração             int64
 11  Descrição Abreviada Infração   object
 12  Enquadramento da Infração      object
 13  Início Vigência da Infração    object
 14  Fim Vigência Infração          float64
 15  Medição Infração               object
 16  Descrição Especie Veículo      object
 17  Descrição Marca Veículo        object
 18  Hora Infração                  int64
 19  Medição Considerada            object
 20  Excesso Verificado             object
 21  Qtd Infrações                  int64
dtypes: float64(1), int64(5), object(16)
memory usage: 879.7+ MB

In [9]:
# INFRAÇÕES 2025
infra_2025_datasets = [
    f"{infra_path}/infracoes_2025/infracoes_2025_01.csv", f"{infra_path}/infracoes_2025/infracoes_2025_02.csv",
    f"{infra_path}/infracoes_2025/infracoes_2025_03.csv", f"{infra_path}/infracoes_2025/infracoes_2025_04.csv",
    f"{infra_path}/infracoes_2025/infracoes_2025_05.csv", f"{infra_path}/infracoes_2025/infracoes_2025_06.csv",
    f"{infra_path}/infracoes_2025/infracoes_2025_07.csv", f"{infra_path}/infracoes_2025/infracoes_2025_08.csv",
    f"{infra_path}/infracoes_2025/infracoes_2025_09.csv", f"{infra_path}/infracoes_2025/infracoes_2025_10.csv",
    f"{infra_path}/infracoes_2025/infracoes_2025_11.csv", f"{infra_path}/infracoes_2025/infracoes_2025_12.csv",
]

infra_2025 = [pd.read_csv(arquivo,sep=";",encoding="ISO-8859-1", low_memory=False) for arquivo in infra_2025_datasets]
df_infra_2025 = pd.concat(infra_2025, ignore_index=True)

df_infra_2025.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10204474 entries, 0 to 10204473
Data columns (total 25 columns):
 #   Column                         Dtype
---  ------                         -----
 0   Número do Auto                 object
 1   Data da Infração (DD/MM/AAAA)  object
 2   Indicador de Abordagem         object
 3   Assinatura do Auto             object
 4   Sentido Trafego                object
 5   UF Infração                    object
 6   BR Infração                    int64
 7   Km Infração                    int64
 8   Município                      object
 9   Indicador Veiculo Estrangeiro  object
 10  UF Placa                       object
 11  Descrição Especie Veículo      object
 12  Descrição Marca Veículo        object
 13  Descrição Tipo Veículo         object
 14  Descrição Modelo Veiculo       object
 15  Código da Infração             int64
 16  Descrição Abreviada Infração   object
 17  Enquadramento da Infração      object
 18  Início Vigência da Infração    object
 19  Fim Vigência Infração          float64
 20  Medição Infração               object
 21  Hora Infração                  int64
 22  Medição Considerada            float64
 23  Excesso Verificado             float64
 24  Qtd Infrações                  int64
dtypes: float64(3), int64(5), object(17)
memory usage: 1.9+ GB

**Tarefa 2: Combinação dos conjuntos de dados**

1 - Gerar dois conjuntos de dados a partir da combinação dos anos: um para acidentes e um para
multas. Nessa combinação, deve existir a identificação dos anos no próprio conjunto de dados
utilizando multiindex.

**A célula abaixo seria a solução para gerar um único DataaFrame com todos os datasets de INFRAÇÕES, porém, mesmo com apenas 3 datasets o Google Colab não é capaz de concatenar tudo em um único DataFrame**

In [ ]:
# Unindo todos os dataframes de infrações em um único dataframe
dataframes = [
    df_infra_2018, df_infra_2021, df_infra_2025
  ]

df_infra_final = pd.concat(dataframes, ignore_index=True)
df_infra_final.info()
df_infra_final.shape

A célula abaixo gera um único DataFrame com os datasets de ACIDENTES

In [16]:
# Todos os arquivos .csv dos acidentes seguem a mesma nomenclatura e
# quantidade de colunas, logo é possível realizar a mesclagem diretamente

# Adiciona labels para exibição multi-index
anos = [2018, 2021, 2025]

# Mesclagem dos datasets de acidentes em um único dataframe
aci_datasets = [
    f"{aci_path}/acidentes_2018/datatran2018.csv",
    f"{aci_path}/acidentes_2021/datatran2021.csv",
    f"{aci_path}/acidentes_2025/datatran2025.csv"
]

dataframes = [pd.read_csv(arquivo,sep=";",encoding="ISO-8859-1") for arquivo in aci_datasets]
df_aci_final = pd.concat(dataframes, keys=anos)
df_aci_final.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 206429 entries, (np.int64(2018), np.int64(0)) to (np.int64(2025), np.int64(72528))
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      206429 non-null  float64
 1   data_inversa            206429 non-null  object
 2   dia_semana              206429 non-null  object
 3   horario                 206429 non-null  object
 4   uf                      206429 non-null  object
 5   br                      206429 non-null  int64
 6   km                      206429 non-null  object
 7   municipio               206429 non-null  object
 8   causa_acidente          206429 non-null  object
 9   tipo_acidente           206406 non-null  object
 10  classificacao_acidente  206426 non-null  object
 11  fase_dia                206429 non-null  object
 12  sentido_via             206429 non-null  object
 13  condicao_metereologica  206429 non-null  object
 14  tipo_pista              206429 non-null  object
 15  tracado_via             206429 non-null  object
 16  uso_solo                206429 non-null  object
 17  pessoas                 206429 non-null  int64
 18  mortos                  206429 non-null  int64
 19  feridos_leves           206429 non-null  int64
 20  feridos_graves          206429 non-null  int64
 21  ilesos                  206429 non-null  int64
 22  ignorados               206429 non-null  int64
 23  feridos                 206429 non-null  int64
 24  veiculos                206429 non-null  int64
 25  latitude                206429 non-null  object
 26  longitude               206429 non-null  object
 27  regional                206427 non-null  object
 28  delegacia               206354 non-null  object
 29  uop                     206313 non-null  object
dtypes: float64(1), int64(9), object(20)
memory usage: 50.8+ MB

**Tarefa 3: Limpeza e preparação dos conjuntos de dados pós-combinação**

**Como não foi possível realizar a mesclagem para gerar o DataFrame de INFRAÇÕES, prosseguirei apenas com o DataFrame de ACIDENTES**

1 - Procurar identificar possíveis inconsistências nos dados de cada conjunto obtido da Tarefa 2: dados
faltosos, dados repetidos ou ooutros problemas;

In [17]:
# Remoção de células duplicadas
df_aci_final.drop_duplicates()

# Dicionário para o preenchimento de células NaN por coluna
estrategias_nan = {
    "causa_acidente":         "Ignorado",
    "fase_dia":               "Ignorado",
    "condicao_metereologica": "Ignorado",
    "tipo_acidente":          "Ignorado",
    "classificacao_acidente": "Ignorado",
    "sentido_via":            "Ignorado",
    "tracado_via":            "Ignorado",
    "tipo_pista":             "Ignorado",
    "uso_solo":               "Ignorado",
    "mortos":                 0,
    "feridos_leves":          0,
    "feridos_graves":         0,
    "ilesos":                 0,
}

# Aplicando apenas nas colunas que existem no DataFrame
for col, valor in estrategias_nan.items():
    if col in df_aci_final.columns:
        df_aci_final[col] = df_aci_final[col].fillna(valor)

df_aci_final.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 206429 entries, (np.int64(2018), np.int64(0)) to (np.int64(2025), np.int64(72528))
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      206429 non-null  float64
 1   data_inversa            206429 non-null  object
 2   dia_semana              206429 non-null  object
 3   horario                 206429 non-null  object
 4   uf                      206429 non-null  object
 5   br                      206429 non-null  int64
 6   km                      206429 non-null  object
 7   municipio               206429 non-null  object
 8   causa_acidente          206429 non-null  object
 9   tipo_acidente           206429 non-null  object
 10  classificacao_acidente  206429 non-null  object
 11  fase_dia                206429 non-null  object
 12  sentido_via             206429 non-null  object
 13  condicao_metereologica  206429 non-null  object
 14  tipo_pista              206429 non-null  object
 15  tracado_via             206429 non-null  object
 16  uso_solo                206429 non-null  object
 17  pessoas                 206429 non-null  int64
 18  mortos                  206429 non-null  int64
 19  feridos_leves           206429 non-null  int64
 20  feridos_graves          206429 non-null  int64
 21  ilesos                  206429 non-null  int64
 22  ignorados               206429 non-null  int64
 23  feridos                 206429 non-null  int64
 24  veiculos                206429 non-null  int64
 25  latitude                206429 non-null  object
 26  longitude               206429 non-null  object
 27  regional                206427 non-null  object
 28  delegacia               206354 non-null  object
 29  uop                     206313 non-null  object
dtypes: float64(1), int64(9), object(20)
memory usage: 50.8+ MB

2 - Transformar variáveis para os tipos corretos:
- variáveis relacionadas a tempo (datas, dias, horas) devem ser tratadas como datetimes;
- variáveis numéricas não podem ser trabalhadas como string;
- variáveis categóricas devem ser tratadas como category

In [18]:
# Convertendo colunas com data e hora para datetime
df_aci_final["data_inversa"] = pd.to_datetime(df_aci_final["data_inversa"])
df_aci_final["horario"] = pd.to_datetime(df_aci_final["horario"], format="%H:%M:%S")

# Convertendo células numéricas para float
cols_numericas = ["km", "latitude", "longitude"]

for col in cols_numericas:
    if df_aci_final[col].dtype == object:  # só aplica str.replace se for string
        df_aci_final[col] = df_aci_final[col].str.replace(",", ".", regex=False)
    df_aci_final[col] = pd.to_numeric(df_aci_final[col], errors='coerce')

df_aci_final[cols_numericas].dtypes

# Convertendo colunas categóricas para category
cols_categoricas = [
    "dia_semana", "uf", "causa_acidente", "tipo_acidente",
    "classificacao_acidente", "fase_dia", "sentido_via",
    "condicao_metereologica", "tipo_pista", "tracado_via", "uso_solo"
]

df_aci_final[cols_categoricas] = df_aci_final[cols_categoricas].astype("category")
df_aci_final.info()
df_aci_final.head()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 206429 entries, (np.int64(2018), np.int64(0)) to (np.int64(2025), np.int64(72528))
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      206429 non-null  float64
 1   data_inversa            206429 non-null  datetime64[ns]
 2   dia_semana              206429 non-null  category
 3   horario                 206429 non-null  datetime64[ns]
 4   uf                      206429 non-null  category
 5   br                      206429 non-null  int64
 6   km                      206429 non-null  float64
 7   municipio               206429 non-null  object
 8   causa_acidente          206429 non-null  category
 9   tipo_acidente           206429 non-null  category
 10  classificacao_acidente  206429 non-null  category
 11  fase_dia                206429 non-null  category
 12  sentido_via             206429 non-null  category
 13  condicao_metereologica  206429 non-null  category
 14  tipo_pista              206429 non-null  category
 15  tracado_via             206429 non-null  category
 16  uso_solo                206429 non-null  category
 17  pessoas                 206429 non-null  int64
 18  mortos                  206429 non-null  int64
 19  feridos_leves           206429 non-null  int64
 20  feridos_graves          206429 non-null  int64
 21  ilesos                  206429 non-null  int64
 22  ignorados               206429 non-null  int64
 23  feridos                 206429 non-null  int64
 24  veiculos                206429 non-null  int64
 25  latitude                206429 non-null  float64
 26  longitude               206429 non-null  float64
 27  regional                206427 non-null  object
 28  delegacia               206354 non-null  object
 29  uop                     206313 non-null  object
dtypes: category(11), datetime64[ns](2), float64(4), int64(9), object(4)
memory usage: 35.9+ MB

              id data_inversa     dia_semana             horario  uf   br  \
2018 0  100027.0   2018-01-01  segunda-feira 1900-01-01 06:00:00  TO  153
     1  100044.0   2018-01-01  segunda-feira 1900-01-01 08:30:00  SE  101
     2  100046.0   2018-01-01  segunda-feira 1900-01-01 08:50:00  TO  153
     3  100052.0   2018-01-01  segunda-feira 1900-01-01 05:30:00  PA  155
     4  100053.0   2018-01-01  segunda-feira 1900-01-01 10:25:00  BA  116

           km            municipio                      causa_acidente  \
2018 0  393.1         RIO DOS BOIS         Falta de Atenção à Condução
     1  123.4    ITAPORANGA DAJUDA  Não guardar distância de segurança
     2  347.0               GUARAI         Falta de Atenção à Condução
     3  221.0  ELDORADO DO CARAJAS                  Ingestão de Álcool
     4  289.6               TUCANO              Ultrapassagem Indevida

                    tipo_acidente  ... feridos_graves ilesos ignorados  \
2018 0            Colisão frontal  ...              1      1         0
     1           Colisão traseira  ...              0      2         0
     2            Colisão lateral  ...              0      2         1
     3            Colisão lateral  ...              0      1         0
     4  Saída de leito carroçável  ...              1      0         1

       feridos veiculos   latitude  longitude  regional  delegacia  \
2018 0       1        2  -9.356414 -48.546103   SPRF-TO   DEL02-TO
     1       0        2 -11.044760 -37.364980   SPRF-SE   DEL02-SE
     2       0        3  -8.952295 -48.500107   SPRF-TO   DEL02-TO
     3       0        2  -6.345512 -49.389626   SPRF-PA   DEL03-PA
     4       1        2 -11.086617 -38.834202   SPRF-BA   DEL02-BA

                     uop
2018 0    UOP02-DEL02-TO
     1    UOP01-DEL02-SE
     2    UOP02-DEL02-TO
     3    UOP01-DEL03-PA
     4  DEL10/2-UOP02/BA

[5 rows x 30 columns]

3 - Ajustar a codificação das variáveis categóricas, de acordo com o dicionário de cada conjunto,
i.e., caso os dados estajem codificados de alguma forma, transformar os valores codificados nos
valores associados, assinalados o dicionário de dados do conjunto.

In [19]:
# Ao analisar o DataFrame, a coluna uso_solo que reflete
# se o acidente ocorreu em ambiente urbano ou rural utiliza
# apenas 'sim'(urbano) e 'não' (rural), necessitando de tratamento

mapa_uso_solo = {
    "Sim": "Urbano",
    "Não": "Rural",
}

df_aci_final["uso_solo"] = df_aci_final["uso_solo"].map(mapa_uso_solo).astype("category")

# Exibindo a coluna para confirmar a mudança
df_aci_final["uso_solo"].head(10)

2018  0    Rural
      1    Rural
      2    Rural
      3    Rural
      4    Rural
      5    Rural
      6    Rural
      7    Rural
      8    Rural
      9    Rural
Name: uso_solo, dtype: category
Categories (2, object): ['Rural', 'Urbano']

**4: Armazenamento dos novos conjuntos de dados após o pré-processamento**

1 - Criar um arquivo .csv do conjunto de dados após a realização das Tarefas 2 e 3;

In [20]:
from google.colab import files

# Última exibição dos dados
print(df_aci_final.info())
print(df_aci_final.describe())
print(df_aci_final.shape)

# Converte o DataFrame de acidentes em um novo arquivo .csv
df_aci_final.to_csv("acidentes_preprocessado.csv", index=False, encoding="utf-8-sig")
# Baixa o arquivo do Google Colab na máquina local
files.download("acidentes_preprocessado.csv")

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 206429 entries, (np.int64(2018), np.int64(0)) to (np.int64(2025), np.int64(72528))
Data columns (total 30 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      206429 non-null  float64
 1   data_inversa            206429 non-null  datetime64[ns]
 2   dia_semana              206429 non-null  category
 3   horario                 206429 non-null  datetime64[ns]
 4   uf                      206429 non-null  category
 5   br                      206429 non-null  int64
 6   km                      206429 non-null  float64
 7   municipio               206429 non-null  object
 8   causa_acidente          206429 non-null  category
 9   tipo_acidente           206429 non-null  category
 10  classificacao_acidente  206429 non-null  category
 11  fase_dia                206429 non-null  category
 12  sentido_via             206429 non-null  category
 13  condicao_metereologica  206429 non-null  category
 14  tipo_pista              206429 non-null  category
 15  tracado_via             206429 non-null  category
 16  uso_solo                206429 non-null  category
 17  pessoas                 206429 non-null  int64
 18  mortos                  206429 non-null  int64
 19  feridos_leves           206429 non-null  int64
 20  feridos_graves          206429 non-null  int64
 21  ilesos                  206429 non-null  int64
 22  ignorados               206429 non-null  int64
 23  feridos                 206429 non-null  int64
 24  veiculos                206429 non-null  int64
 25  latitude                206429 non-null  float64
 26  longitude               206429 non-null  float64
 27  regional                206427 non-null  object
 28  delegacia               206354 non-null  object
 29  uop                     206313 non-null  object
dtypes: category(11), datetime64[ns](2), float64(4), int64(9), object(4)
memory usage: 35.9+ MB
None
                  id                data_inversa  \
count  206429.000000                      206429
mean   410180.990801  2021-11-24 21:23:06.066880
min     99973.000000         2018-01-01 00:00:00
25%    163008.000000         2018-09-28 00:00:00
50%    371838.000000         2021-07-16 00:00:00
75%    687091.000000         2025-04-21 00:00:00
max    758186.000000         2025-12-31 00:00:00
std    234215.322350                         NaN

                             horario             br             km  \
count                         206429  206429.000000  206429.000000
mean   1900-01-01 13:21:29.381627648     211.182232     259.638849
min              1900-01-01 00:00:00       0.000000       0.000000
25%              1900-01-01 08:20:00     101.000000      76.100000
50%              1900-01-01 14:05:00     158.000000     193.900000
75%              1900-01-01 18:25:00     324.000000     408.900000
max              1900-01-01 23:59:00     498.000000    1454.500000
std                              NaN     130.121190     227.053856

             pessoas         mortos  feridos_leves  feridos_graves  \
count  206429.000000  206429.000000  206429.000000   206429.000000
mean        2.539076       0.080967       0.855960        0.268485
min         1.000000       0.000000       0.000000        0.000000
25%         2.000000       0.000000       0.000000        0.000000
50%         2.000000       0.000000       1.000000        0.000000
75%         3.000000       0.000000       1.000000        0.000000
max        81.000000      19.000000      58.000000       28.000000
std         2.060870       0.334626       1.058428        0.610916

              ilesos      ignorados        feridos       veiculos  \
count  206429.000000  206429.000000  206429.000000  206429.000000
mean        1.035087       0.380145       1.124445       1.974713
min         0.000000       0.000000       0.000000       1.000000
25%         0.000000       0.000000       1.000000       1.000000
50%         1.000000       0.000000       1.000000       2.000000
75%         1.000000       1.000000       1.000000       2.000000
max        71.000000      81.000000      66.000000      82.000000
std         1.602945       0.812157       1.181226       1.086641

            latitude      longitude
count  206429.000000  206429.000000
mean      -18.796774     -46.562095
min       -33.689819     -72.665988
25%       -25.201851     -50.219600
50%       -20.379762     -47.603606
75%       -12.723321     -42.465730
max         4.461419     -34.827690
std         7.784634       6.191567
(206429, 30)

2 - Fazer upload desse conjunto de dados para algum armazenamento em nuvem para uso em ativi-
dades posteriores (sugestão: github ou Gdrive).

- Repositório com o notebook: https://github.com/arthur-dnts/AED-Exercicios